(() => {
  G = newGame(); initRun(); statCache = null;
  const D = {};
  const rn = RARITY.map(r => r.name);
  const pn = rarityProbs(false), pb = rarityProbs(true);
  D.rarity = RARITY.map((r, i) => ({ name: r.name, color: r.color, weight: r.w, pNormal: pn[i], pBoss: pb[i], mult: r.mult, floors: r.floors, affixes: r.affixes, affixStrength: affixMult(i), scrap: SCRAP.perRarity[i], sell: Math.pow(1 + i, 2), prefix: PREFIXES[i].slice(0, 3) }));
  const mpN = { power: modProbs(false, 'power'), flavour: modProbs(false, 'flavour') }, mpB = { power: modProbs(true, 'power'), flavour: modProbs(true, 'flavour') };
  D.modifiers = MODIFIERS.map(m => ({ kind: m.kind, name: m.name, icon: m.icon, oneIn: m.oneIn, mult: m.mult, floors: m.floors, extra: m.extra || 0, aff: m.aff || null, pNormal: mpN[m.kind][m.id], pBoss: mpB[m.kind][m.id], fx: m.fx }));
  D.affixes = Object.entries(AFFIXES).map(([k, a]) => ({ name: a.name.replace(/^% /, ''), min: a.min, max: a.max, cap: a.cap || null }));
  D.slots = Object.entries(SLOT_BASE).map(([k, b]) => ({ slot: k, icon: SLOTS[k].icon, base: b, names: SLOTS[k].names }));
  D.item = { floorGrowth: ITEM_FLOOR_GROWTH, equipMinGain: EQUIP_MIN_GAIN, dropChance: 0.07, earlyLoot: [1, 10, 20, 30, 40, 50, 60].map(f => [f, earlyLoot(f)]), setChance: SET_CHANCE, findOdds: FIND_ODDS };
  D.sets = Object.entries(GEAR_SETS).map(([k, s]) => ({ name: s.name, color: s.color, two: s[2], three: s[3], four: s[4], zones: s.zones || [] })); D.setHome = SET_HOME;
  D.amuletTiers = AMULET_TIERS.map((t, i, a) => ({ name: t.name, color: t.color, weight: t.w, p: t.w / a.reduce((x, y) => x + y.w, 0), power: t.power, charms: t.charms }));
  D.amuletStats = Object.entries(AMULET_STATS).map(([k, s]) => ({ name: s.name, desc: s.desc, per: s.per }));
  D.amulet = { chance: AMULET_CHANCE };
  D.hero = Object.assign({}, HERO, { speedCap: ATTACK_SPEED_CAP, overflowHp: OVERFLOW_HP_SHARE });
  D.skills = Object.entries(SKILLS).map(([k, s]) => ({ name: s.name, icon: s.icon, lvl: s.lvl, cd: s.cd, desc: s.desc, evo: SKILL_EVO[k] }));
  D.skillRanks = SKILL_RANKS;
  D.upgrades = Object.entries(UPGRADES).map(([k, u]) => ({ key: k, name: u.name, icon: u.icon, desc: u.desc, base: u.base, growth: u.growth, max: u.max || null, at: u.at, mastery: u.mastery ? Object.entries(u.mastery).map(([s, m]) => `×${m.toFixed(4)} ${MASTERY_NAMES[s]}`)[0] : null, tab: Object.entries(UPG_TABS).find(([, t]) => t.keys.includes(k))?.[1].name }));
  D.bal = Object.assign({}, BAL, { masteryGrowth: MASTERY_GROWTH });
  D.perks = Object.entries(PERKS).map(([k, p]) => ({ name: p.name, desc: p.desc, base: p.base, growth: p.growth, max: p.max || null, at: p.at, costs: Array.from({ length: Math.min(p.max || 6, 6) }, (_, n) => { G.perks[k] = n; return perkCost(k); }) }));
  G.perks = newGame().perks;
  D.relics = Object.entries(RELICS).map(([k, r]) => ({ name: r.name, icon: r.icon, cost: r.cost, desc: r.desc }));
  D.gemShop = Object.entries(GEM_SHOP).map(([k, s]) => ({ name: s.name, icon: s.icon, cost: s.cost, desc: s.desc }));
  D.gems = { perAch: GEMS.perAch, chest: GEMS.chestChance, cookie: GEMS.cookie, boss: [20, 100, 200, 400, 600, 1000].map(f => [f, gemsForBoss(f)]) };
  D.bounties = BOUNTY_TYPES.map(b => ({ text: b.text('N'), n: b.n })); D.bountyReward = BOUNTY_REWARD; D.bountyAt = BOUNTY_AT;
  D.bestiary = BESTIARY;
  D.pets = Object.entries(COSMETICS.pet.items).slice(1).map(([id, p]) => ({ name: p.name, fx: p.fx || null, from: (ACHIEVEMENTS.find(a => a.cos === id) || {}).name || null }));
  D.petDrop = PET_DROP;
  D.cookies = (() => { const tot = COOKIES.reduce((a, c) => a + c[0], 0); return COOKIES.map(c => ({ text: c[2], p: c[0] / tot })); })();
  D.traits = (() => { const tot = TRAITS.reduce((a, t) => a + t.w, 0); return TRAITS.map(t => ({ name: t.name, icon: t.icon, p: t.w / tot, desc: t.desc })); })();
  D.champion = CHAMPION; D.traitChance = [5, 20, 50, 100].map(f => [f, traitChance(f)]);
  D.bossAbilities = BOSS_ABILITIES;
  D.zones = ZONES.map((z, i) => ({ i, name: z.name, floors: `${i * FLOORS_PER_ZONE + 1}–${(i + 1) * FLOORS_PER_ZONE}`, mobs: z.mobs.map(m => ENEMIES[m] ? ENEMIES[m].name : m), guard: z.guard.name, guardAb: bossAbilities(z, 'guard', 2).join(' + '), lord: z.boss.name, lordAb: bossAbilities(z, 'lord', 2).join(' + '), fx: z.fx ? `${z.fx.name}: ${z.fx.desc}` : '', sets: zoneSets(z).map(id => GEAR_SETS[id].name) }));
  D.enemyCount = Object.keys(ENEMIES).length;
  D.specials = Object.entries(SPECIAL_STAGES).map(([k, s]) => ({ name: s.name, icon: s.icon, desc: s.desc })); D.specialChance = SPECIAL_CHANCE;
  D.scrap = SCRAP; D.chests = Object.entries(SCRAP_CHESTS).map(([k, c]) => ({ name: c.name, icon: c.icon, cost: c.cost, range: c.maxR != null ? `${rn[c.minR]}–${rn[c.maxR]}` : `${rn[c.minR]} or better`, mod: c.mod || 1 })); D.chestJackpot = CHEST_JACKPOT; D.chestTop = CHEST_TOP_MODS; D.replayScrap = REPLAY_SCRAP; D.chestIlvl = CHEST_ILVL; D.chestGrowth = CHEST_GROWTH;
  D.forge = FORGE; D.reforge = REFORGE; D.temper = TEMPER; D.stashMax = STASH_MAX;
  D.chestsWorld = CHEST;
  D.features = Object.entries(FEATURES).filter(([k]) => k !== 'challenges').map(([k, f]) => ({ at: f.at, name: f.name }));
  D.stars = { at: STAR.at, boss: STAR.boss, rush: STAR.rush, list: Object.values(CONSTELLATIONS).map(c => ({ name: c.name, icon: c.icon, color: c.color, costs: c.nodes.map((_, i) => c.base * Math.pow(2, i)), nodes: c.nodes.map(starFxText) })) };
  D.awaken = { exp: AWAKEN.exp, at: AWAKEN.at, per: AWAKEN.per, souls: AWAKEN.souls, power: AWAKEN.power, caps: Object.entries(AWAKEN.caps).map(([k, [per, most]]) => ({ name: PERKS[k].name, per, most })), examples: [1e9, 1e10, 1e11, 1e12, 1e13, 1e15].map(s => [s, Math.floor(Math.pow(s / AWAKEN.per, AWAKEN.exp))]) };
  D.exped = { at: EXPED.at, slots: EXPED.slots, petMax: PET_MAX_LVL, list: Object.values(EXPEDITIONS).map(e => ({ name: e.name, icon: e.icon, secs: e.secs, gems: e.gems, scrap: e.scrap, insight: e.insight, dust: e.dust, items: e.items, xp: e.xp })) };
  D.lab = { at: LAB.at, list: Object.values(RESEARCH).map(r => ({ name: r.name, icon: r.icon, cost: r.cost, hours: r.hours, desc: r.desc })) };
  D.oaths = { at: OATH.at, pickUntil: OATH.pickUntil, max: OATH.max, per: OATH.per, list: Object.values(OATHS).map(o => ({ name: o.name, icon: o.icon, color: o.color, up: oathText(o.up), down: oathText(o.down), desc: o.desc })) };
  D.events = { at: EVENT.at, every: EVENT.every, secs: EVENT.secs, list: Object.values(WORLD_EVENTS).map(e => ({ name: e.name, icon: e.icon, desc: e.desc })) };
  D.fate = Object.entries(FATE).map(([t, n]) => ({ name: RARITY[t].name, every: n }));
  D.challenges = Object.values(CHALLENGES).map(c => ({ name: c.name, icon: c.icon, rule: c.rule, goal: c.goal, reward: chalRewardText(c) }));
  D.rush = { n: RUSH_LIST.length, at: RUSH.at, cooldown: RUSH.cooldown, walk: RUSH.walk, step: RUSH.step, examples: [100, 300, 500, 1000].map(b => { G.stats.rushFloor = b; return [b, rushFloor(0), rushStep(), rushFloor(RUSH_LIST.length - 1)]; }) };
  G.stats.rushFloor = 0;
  D.hero.critBase = CRIT_BASE;
  D.enemy = { hpGrowth: ENEMY_HP_GROWTH, atkGrowth: ENEMY_ATK_GROWTH, tough: ENEMY_TOUGH, toughStart: TOUGH_START, toughRamp: TOUGH_RAMP, atkExtra: ATK_EXTRA, atkExtraFrom: ATK_EXTRA_FROM, lap: LAP, lapStep: LAP_ATK_STEP, lapFloors: FLOORS_PER_ZONE * ZONES.length, bossHp: 12, bossAtk: 2.2, bossTime: 30 };
  D.floorTable = [1, 10, 25, 50, 100, 200, 400, 401, 800, 801].map(f => { const b = floorBase(f); return { f, lap: zoneTier(f) + 1, hp: b.hp, atk: b.atk, gold: b.gold, xp: b.xp, wave: waveSize(f) }; });
  D.economy = { goldGrowth: GOLD_FLOOR_GROWTH, xpGrowth: XP_FLOOR_GROWTH, xpLevel: XP_LEVEL_GROWTH, replayBonus: REPLAY_BONUS, replay: REPLAY, soulGrowth: SOUL_FLOOR_GROWTH, rebirthMin: REBIRTH_MIN_FLOOR, souls: [30, 50, 100, 150, 200, 300, 400].map(f => [f, soulsFor(f)]), achBonus: ACH_BONUS, headstartPer: HEADSTART_PER, perkCompound: PERK_COMPOUND };
  D.retry = [2, 10, 25, 40, 57, 100].map(f => { G.floor = f; return [f, retryTime()]; }); G.floor = 1;
  D.achievements = Object.entries(ACH_CATS).map(([c, name]) => ({ cat: name, list: ACHIEVEMENTS.filter(a => a.cat === c).map(a => ({ name: a.name, desc: a.desc, cos: a.cos ? (cosmeticById(a.cos) || {}).name : null })) }));
  D.cosmetics = Object.entries(COSMETICS).map(([c, C]) => ({ cat: C.name, n: Object.keys(C.items).length }));
  D.counts = { achievements: ACHIEVEMENTS.length, zones: ZONES.length, enemies: Object.keys(ENEMIES).length, bosses: ZONES.length * 2, modifiers: MODIFIERS.length, cosmetics: Object.values(COSMETICS).reduce((a, C) => a + Object.keys(C.items).length, 0) };
  return JSON.stringify(D);
})()
